<a href="https://colab.research.google.com/github/jessguerzoni/Python/blob/main/AulaNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
import numpy as np
#numpy array unidimensional
a = np.array([1,2,3])
#numpy array bidimensional (matriz)

b= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


Criando array com numpy


In [ ]:
#estrutura uma matriz de 1

Mtz=np.ones((5,5))
print(Mtz)

Mtz=np.arange(10)
print(Mtz)

arr=np.arange(10,30,2)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18 20 22 24 26 28]


Operações numpy array

In [ ]:
ar1=np.array([3,4,6,2])
ar2=np.array([1,7,9,3])

#menor e maior elemento
print(ar1.min(),ar1.max())
#o indice onde eles estao
print(ar1.argmin(),ar1.argmax())

print(ar2.min(),ar2.max())
print(ar2.argmin(),ar2.argmax())

#media
print(ar1.mean(),ar2.mean())
print(ar2.sum())

#operações basicas
print(ar1+ar2)
print(ar1-ar2)
print(ar1*ar2)
print(ar1/ar2)

#concatenar(misturar)

print(np.concatenate((ar1,ar2)))

2 6
3 2
1 9
0 2
3.75 5.0
20
[ 4 11 15  5]
[ 2 -3 -3 -1]
[ 3 28 54  6]
[3.         0.57142857 0.66666667 0.66666667]
[3 4 6 2 1 7 9 3]


Reshape de numpy array


In [ ]:
mtz=np.arange(9)
print(mtz)

#dar um reshape
mtz2=np.arange(9).reshape(3,3)
print(mtz2)

#numero de eleementos
print(mtz2.size)

#formato
print(mtz2.shape)
#numero de dimensoes
print(mtz2.ndim)



[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
9
(3, 3)
2


Operaçoes das linhas e colunas

In [ ]:
mtz2=np.arange(9).reshape(3,3)
print(mtz2)

print(mtz2.sum(axis=0)) #soma coluna
print(mtz2.sum(axis=1)) #soma linha

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]
[ 3 12 21]


broadcasting (operacao entre um vetor e um escalar)

In [ ]:
print(mtz2/2)



[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


Elementos aleatorios

In [ ]:
np.random.seed(10)
ar1=np.random.randint(20,50,[5,5])
print(ar1)

#extrair elementos unicos

#numeros unicos e quantas vezes ele se repete
print(np.unique(ar1,return_counts=True))



[[29 49 24 35 20]
 [37 47 48 45 49]
 [36 49 37 46 28]
 [29 20 30 28 42]
 [24 39 36 24 35]]
(array([20, 24, 28, 29, 30, 35, 36, 37, 39, 42, 45, 46, 47, 48, 49]), array([2, 3, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 3]))
