<a href="https://colab.research.google.com/github/jessguerzoni/Python/blob/main/CAP4_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Crie dois NumPy Arrays unidimensionais de tamanho
8
: um formado apenas
por1’s
e outro formado por números aleatórios entre 0 e 9
. Some estes dois
NumPy Arrays
e guarde
o resultado dentro de um terceiro NumPy Array. Por
fim, faça
o seguinte. Se
a soma de todos os elementos do Array resultante for >= 40
, remodele este
NumPy Array para se tornar uma matriz com mais linhas do que colunas

In [30]:
import numpy as np

A1=np.ones(8)
A2=np.random.randint(0,10,8)
A3=A1+A2
soma=A3.sum()

print(A1)
print(A2)
print(A3)
print(soma)
if(soma>=40):
  print(A3.reshape(2,4))
else:
  print(A3.reshape(4,2))

[1. 1. 1. 1. 1. 1. 1. 1.]
[5 4 6 0 2 3 3 4]
[6. 5. 7. 1. 3. 4. 4. 5.]
35.0
[[6. 5.]
 [7. 1.]
 [3. 4.]
 [4. 5.]]


Crie dois NumPy Arrays unidimensionais
: um de números pares de
0
à 51
e
outro também de números pares de 100 até 50
. Em seguida, os concatene
e
mostre os resultados ordenados

In [32]:
import numpy as np

A1=np.arange(0,52,2)
A2=np.arange(100,49,-2)

#concatenando
A3=np.concatenate((A1,A2))

print(A1)
print(A2)
#sort: ordena em ordem crescente
print(np.sort(A3))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


3. Mini Campo Minado
a) Crie um NumPy Array
2
x
2 formado apenas por
0’s
b) Em seguida, adicione um número
1 em uma posição aleatória desta matriz
;
c) Faça uma entrada de dados para solicitar
o usuário que faça uma jogada
(selecione uma posição da matriz)
I. Se ele selecionar todas as posições em que
o número
1 não se encontra, mostre
a
mensagem
“Congratulations
! You beat the game!
:
)
”
II. Senão, se dentro das
3 primeiras jogadas ele achar
o número
1
, mostre
a mensagem
“Game Over!
:
( Try Again!
”

In [50]:
import numpy as np

A1=np.zeros((2,2))
L=np.random.randint(0,2)
C=np.random.randint(0,2)

A1[L,C]=1

Ent=int(input("Entre com o valor da linha: "))
Ent2=int(input("Entre com o valor da coluna:"))

print(A1)


if A1[Ent,Ent2] == 1:
  print("Game Over! :  (Try Again!)")
else:
  print("Congratulations ! You beat the game! :)")

Entre com o valor da linha: 1
Entre com o valor da coluna:0
[[0. 1.]
 [0. 0.]]
Congratulations ! You beat the game! :)


4. Crie uma matriz de tamanho qualquer. Extraia seu número de linhas
e
colunas, multiplique
-os,
e diga se esta matriz poderia se tornar um vetor
unidimensional com número par ou ímpar de elemento

In [52]:
import numpy as np

import numpy as np

matriz = np.array([[1, 2, 3],[4, 5, 6][7,8,9]])

linhas = matriz.shape[0]

colunas = matriz.shape[1]

total = linhas * colunas


if total % 2 == 0:
    print("Se torna um vetor com numeros pares.")
else:
    print("Se torna um vetor com numeros ímpares")



[]


5. Crie uma matriz de tamanho 4x4 formada por números aleatórios inteiros
entre
1
e 50 (use seed
= 10 antes)
a) Mostre
o resultado da média de cada linha
e cada coluna da matriz
gerada
b) Apresente
o maior valor das médias das linhas
e também das colunas
c) Mostre
a quantidade de aparições de cada um dos números gerados na
matriz
. Em seguida, mostre apenas os números que aparecem
2 vezes

In [55]:
import numpy as np
np.random.seed(10)

mtz = np.random.randint(1, 51,[4, 4])

print(mtz)

#a)Média
media_linhas = np.mean(mtz, axis=1)
media_colunas = np.mean(mtz, axis=0)

print(media_linhas)

print(media_colunas)

#b) Maior media de linhas e colunas
maior_media_linhas = np.max(media_linhas)
maior_media_colunas = np.max(media_colunas)

print("Maior média das linhas:", maior_media_linhas)
print("Maior média das colunas:", maior_media_colunas)

#c)Quantas vezes o numero aparece e quem aparece 2x
v, qtde = np.unique(mtz, return_counts=True)


for valor, quantidade in zip(v, qtde):
    print(f"Número {v}: {qtde} vez(es)")

vdup = v[qtde == 2]

print(vdup)

[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]
[16.   33.75 34.5  23.75]
[29.75 24.25 33.75 20.25]
Maior média das linhas: 34.5
Maior média das colunas: 33.75

Quantidade de aparições:
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
Número [ 1  9 10 16 26 29 30 37 41 43 49 50]: [2 1 2 1 1 1 2 1 1 1 1 2] vez(es)
N